sudo: required
language: java
dist: xenial
jdk:
- openjdk11
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_7354dd005c57_key -iv $encrypted_7354dd005c57_iv
  -in travis/helseci.key.enc -out travis/helseci.key -d
- git clone https://github.com/navikt/github-apps-support.git
- export PATH=`pwd`/github-apps-support/bin:$PATH
- export GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./travis/helseci.key
  $GITHUB_APP_ID`)
- export COMMIT_SHORT=$(git rev-parse --short HEAD)
- echo -e "machine api.github.com login x-access-token password $GH_TOKEN" > ~/.netrc
script:
- "./gradlew build && docker build --pull -t $DOCKER_IMG_NAME:$COMMIT_SHORT ."
- |
  set -e
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    docker push $DOCKER_IMG_NAME:$COMMIT_SHORT

    PREPROD_NAISERATOR=$(docker run -v ${PWD}:/workdir mikefarah/yq yq r nais-preprod.yaml -j)
    PREPROD_NAISERATOR=$(echo $PREPROD_NAISERATOR | jq '.spec.image = "'$DOCKER_IMG_NAME':'$COMMIT_SHORT'"' -c)

    PREPROD_DEPLOYMENT=$(cat deployment.json | jq '.payload.kubernetes.resources += ['$PREPROD_NAISERATOR']')
    PREPROD_DEPLOYMENT=$(echo $PREPROD_DEPLOYMENT | jq '.environment = "dev-fss"')
    PREPROD_DEPLOYMENT=$(echo $PREPROD_DEPLOYMENT | jq '.ref = "'$COMMIT_SHORT'"')

    curl -i -n \
      -X POST \
      -d "$PREPROD_DEPLOYMENT" \
      -H "Accept: application/vnd.github.ant-man-preview+json" \
      https://api.github.com/repos/navikt/helse-spa/deployments

    PROD_NAISERATOR=$(docker run -v ${PWD}:/workdir mikefarah/yq yq r nais-prod.yaml -j)
    PROD_NAISERATOR=$(echo $PROD_NAISERATOR | jq '.spec.image = "'$DOCKER_IMG_NAME':'$COMMIT_SHORT'"' -c)

    PROD_DEPLOYMENT=$(cat deployment.json | jq '.payload.kubernetes.resources += ['$PROD_NAISERATOR']')
    PROD_DEPLOYMENT=$(echo $PROD_DEPLOYMENT | jq '.environment = "prod-fss"')
    PROD_DEPLOYMENT=$(echo $PROD_DEPLOYMENT | jq '.ref = "'$COMMIT_SHORT'"')

    curl -i -n \
      -X POST \
      -d "$PROD_DEPLOYMENT" \
      -H "Accept: application/vnd.github.ant-man-preview+json" \
      https://api.github.com/repos/navikt/helse-spa/deployments
  fi
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
  - ./triggerbuild.sh helse-e2e
env:
  global:
  - APP_NAME=spa
  - DOCKER_IMG_NAME=navikt/spa
  - GITHUB_APP_ID=19726
  - secure: xtMH0Q/LclYRGzZaPwwvvlCDGMCRm07o7TQ0UBflWjApEr5YFnYdX41+gDqfdoFpZ9oA5sFsenOvSjLLDBgefSRU2uZf82dKihOD5CnTbsEPHF8vUnwX1jflTQA6gL8dQk/y0XIt1MuICt9wRp3GXPp73y343qLpsZzS0wp7QJjm9zaWLmVJ/01PV+jqkfCHKoLP0FkxnbYlCMVarEJ1wcx/qM99z7Sb+7pPzkGJR1T3EMdNj5a0Y1Q0jcycpBmZbaWT1N0+KzJN1XsMFnKNtOH+zaodAdvlU/Vi9qGAmTdva8VmJkKDzU/PYDakJ61UTADykFrlIK6s2oMtlJoVN4wzevhZaKJUiQXDOjFRddp2ztAstCp/IqgAgdjCa1eqZlcC/ls1acJ5I6S3g59kgajzG5i4HrLa0vT94D1swD23c9mj2RjuBn0/PxVZ7gEUDE7HHciirssqhgy2A/RqcajTOaGoCW655h2LiRFSZhQIGCtbXCMiGAHtFb525RShEh/dSvo4DfkbKcyqt55aBfDn4sW2qU64Nx4a9/5HEtsdVB7xZ4GxO0aJouR/Js7xKbzR3SKE4vdIpeS45gQcfa48Z/5yniQMJAqKCp2m7JlcvEJzSrzVoS2lLyEEoncx2CIvRvVNE1ahwzZOvpbHpWk4kE47hFd7qWLiNnQWhMk=
  - secure: K50ecN7bqHvsVzP4QsJkfsFnI/4I1hs2IWLBkuxNh7YtroOF1TfiKu3d8JmvMU4vpZ+L6U7Jkwcf95VhFWCfqM2xOEPEZTv0bFkX3w/6TmpAEhCmZzjPdbEEwYDqmjmQBeOHbUifKkn8uYTGKCl47Sc3E0sgdd8RBiYURyEMK41ks/akamObPXXspl0jJcMGa/XZ41OhyK+jWnmLh8Zdt98Y50MBvGW/Jw8yWn43iNVQyedQCcbnMQSOQu2PxXErTOzrmZ+s3TtT1IuiE5X0fFUXte6DpQQbEppjNaBUU9kMgCRA0h3EEeye2IcbSVT0ikWGdz2TPclsnCL9foiw6qgzlI5BSA6I7FF89YP7xZ1ysV6ix6nqQlZSF7ZuDDEM1DbMgLD8BryB7uJOWjs2f3KHepXYuzLX8meO3DoTXotCGFndrtzKjGFDc9ymtYwszjbN7zQBy0Y494fSDtZejP2ulCJicoO7tU8LecH4QX+WdxudQh1vxIRnwIqjj4sjcnsRumpuNbrW0pO6iMdyPzzFRDLbEcBOGWL9X03wf6h88dHMNkByeSpd2LEcykLiqSiagBeyVBguQyQ0LIo8ZR+NYmGgrWtm9QMCsrc5nx6PxU3o3F2WUqJ7pTg88URFHRM0tyhuYIi5Jq+2h53wNmk5Al2SinUos7xgOxC3ZBg=
  - secure: lK5Za+5Py8OzHftU7RbDokbBV81ImScmZB4OhJmEqeHLAYxzC9ntY3R/40vtnDG1PvqiND4pKG4aGy7WBCH5NEeadVcapY2k/lfuSpAe+ij1NDhdHv8K/DB3fdSwk1qyx0VQhihi7cBgKd/vQKexpbiCBw4FahI93uObErrYi4/ASDHfx0x0OqHmYjEPDQraSx8Y2EzMjw+DDwDgTAUN0z9ks0hh0T4zuw17E9Q6tjbTNa9nv42E35cr88Wx/OnPTj+eqtlwn3vMWPiIrUzSE7Hn7UZLA69A+4LHFaEl4VTrGJlwEA4WLfVO6R35kZuM0okazY4cLOSVZyLZQASG2YrbcPgMZAUuZnm276xwk6qhi6pFMlotJ5Mr7oDaw9ZZMn7Yd/G2FF/wbZGbA9/RctIT3mtTCypwvsihkRjIgcCLRCRiEq8CbCYUcl874KQjC1KGhLfB5P05JBxcYru7mX8y/jznYFEk1xyk8xL/MiC6XWl0lgPYgmqoJXFZQJRsOOAqxSLG1EpgMP1rQMzHW5fE5pV+/H8zSzxVoKYa2FC3eUpLp3TPPbKrdCYKzyWh4m6CLFGOyd2f7z9iuayudM6lR0N/ZrShlir4k2HQOrsjr70qnzpES8JDi5Hf6WAasbhvpMHDYIXOaOwWlwNcE8ERXer+D3rRO7ROeg7tWN8=
notifications:
  slack:
    secure: b+zxosUVV0YW5nBBYBu7SaPt+udcuCMxa/PipDoTkySMAlSqAiMZG+MX930GqXTRxVJB43dsug/8VDfpEWC28vzinHzNdEguCdmibew3AY/X56iJeVP+dRDiB4Q+AwF1uFtayEj19eiieNOKq2uJ0vuITveWAOGrDDI0/WsXZb34Ju9AMR2Zdkv1VVwWwUa/aoykPDvFANLD/JzPX+GHpbKtK0TsV3APVChfAD2jy50wGuPzNjr60i0pc5xmS6LvebtnQ024mUeEIA34VyoKIaNN4OFtNUjx3RvvCrkVdzjuf9fAYPb4DvXEmtzU24AqQ8JOo1jHmxRDJeuOSmoFWMUnb6GOsyclxNtnNAtOsSpX5TkLGMj+DgMxd1iUEl3d0JZcTM3qsLjpTdnV75Wjf7j72J42AdQuLdRn1pS1CB6VgU48mRjEg/j0A7VaV0ruvAN5Zk1QtIQGiGIYNi+wztb0WNYaj2RXd/AHmrIYOOX2HoL4D2NV7VjEb0/YsygAxTq4LQFZ8TcYFmLVjzJTf4zycsONT3rOFW8WiVWuqTSLTap/fOnwdYxpcjKXMpNjVfLfX0/CqA2Y3flmzYlneIZ1w3a7641kT0TNrO8/0r/d2dtc0wWejvc5lEe93qRKZu72ZJHmSqmBg5dFhDjmsoHLgUMKwpRjsTOjnw0AFv0=
