sudo: required
language: java
jdk:
- openjdk11
services:
- docker
before_install:
- git clone https://github.com/navikt/github-apps-support.git
- export PATH=`pwd`/github-apps-support/bin:$PATH
- export GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./travis/helseci.key
  $GITHUB_APP_ID`)
- export COMMIT_SHORT=$(git rev-parse --short HEAD)
- export ORIGINAL_COMMITTER=$(git log -1 --pretty=format:'%an <%ae>')
- echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
script:
- "./gradlew check"
- "./gradlew build"
- docker build --pull -t $DOCKER_IMG_NAME:$COMMIT_SHORT .
- |
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    docker push $DOCKER_IMG_NAME:$COMMIT_SHORT

    git clone https://x-access-token:$GH_TOKEN@github.com/navikt/helse-iac.git

    cd helse-iac
    ./set-image.sh preprod/$APP_NAME/naiserator.yaml $DOCKER_IMG_NAME:$COMMIT_SHORT
    ./set-image.sh prod/$APP_NAME/naiserator.yaml $DOCKER_IMG_NAME:$COMMIT_SHORT

    git config user.name team-helse[bot]
    git config user.email team-helse[bot]@users.noreply.github.com

    git add preprod/$APP_NAME/naiserator.yaml
    git add prod/$APP_NAME/naiserator.yaml
    git commit -m "Bump $APP_NAME" -m "Caused by $TRAVIS_BUILD_WEB_URL" --author "$ORIGINAL_COMMITTER"

    git push https://x-access-token:$GH_TOKEN@github.com/navikt/helse-iac.git master

    cd ..
    fi
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - APP_NAME=spa
  - DOCKER_IMG_NAME=navikt/spa
  - GITHUB_APP_ID=19726

