apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: {{team}}
  name: spa
  namespace: default
spec:
  image: {{image}}:{{tag}}
  port: 8080
  liveness:
    failureThreshold: 10
    initialDelay: 20
    path: isalive
    periodSeconds: 5
    timeout: 1
  readiness:
    initialDelay: 20
    path: isready
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
  env:
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
  - name: SECURITY_TOKEN_SERVICE_REST_URL
    value: http://security-token-service
